AllCops:
    NewCops: enable
    TargetRubyVersion: 2.0
Metrics/AbcSize:
    Max: 24
Metrics/BlockLength:
    Max: 80
Metrics/CyclomaticComplexity:
    Max: 5
Metrics/MethodLength:
    Max: 13
Naming/MethodParameterName:
    Enabled: false
Metrics/ParameterLists:
    Max: 7
Naming/VariableNumber:
    Enabled: false
Style/FrozenStringLiteralComment:
    Enabled: false
