plugins:
    rubocop-rspec

AllCops:
    NewCops: enable
    TargetRubyVersion: 2.0
Metrics/AbcSize:
    Max: 24
Metrics/BlockLength:
    Max: 80
Metrics/CyclomaticComplexity:
    Max: 5
Metrics/MethodLength:
    Max: 13
Naming/MethodParameterName:
    Enabled: false
Metrics/ParameterLists:
    Max: 7
Naming/VariableNumber:
    Enabled: false
RSpec/DescribeClass:
    Enabled: false
RSpec/ExampleLength:
    Max: 8
RSpec/LeakyLocalVariable:
    Enabled: false
RSpec/MultipleDescribes:
    Enabled: false
RSpec/MultipleExpectations:
    Max: 4
Style/FrozenStringLiteralComment:
    Enabled: false
